services:
  adminer:
    image: adminer
    networks:
      - data
    restart: on-failure
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}

  db:
    image: postgres:18-alpine
    networks:
      - data
    restart: on-failure
    volumes:
      - ./db-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    restart: on-failure
    networks:
      - data
    build:
      context: backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${BACKEND_PORT}
    depends_on:
      - db

  frontend:
    restart: on-failure
    build:
      context: frontend
    environment:
      - VITE_API_URL=${VITE_API_SERVER}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - ${FRONTEND_PORT}

networks:
  data:
